### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stevenpetryk** [chiptune/js#1]
Hey @chiptune, could you add a license to this? I'd like to know whether I can use it/modify it for use in a company project for @teepsllc :)

Edit: the starfield specifically.

**Comment by chiptune** [comment]
Hello @stevenpetryk ! well I don't know how and where to add a license but if I choose one it will be surely the famous WTFPL one :D

→ http://www.wtfpl.net/txt/copying/

**Comment by stevenpetryk** [comment]
Sweet, thanks <3

You can put it in the root of the repo as a file named LICENSE.txt. I'll make a PR for you.

**Comment by chiptune** [comment]
DONE!

Also I updated a bit the starfield by converting the star's double array to object, more modern code :D
